In [1]:
#Import Libraries 
import pandas as pd
import numpy as np
import nltk

In [2]:
#Import Dataset/Read Dataset
df = pd.read_csv("spam.csv", encoding='latin-1')

In [31]:
df

      label                                            message
0         0  go until jurong point crazy available only in ...
1         0                            ok lar joking wif u oni
2         1  free entry in 2 a wkly comp to win fa cup fina...
3         0        u dun say so early hor u c already then say
4         0  nah i dont think he goes to usf he lives aroun...
...     ...                                                ...
5567      1  this is the 2nd time we have tried 2 contact u...
5568      0                will ì b going to esplanade fr home
5569      0  pity  was in mood for that soany other suggest...
5570      0  the guy did some bitching but i acted like id ...
5571      0                          rofl its true to its name

[5572 rows x 2 columns]

In [4]:
#Select Important Columns and delete extra columns 
df = df[['v1','v2']].copy()

In [5]:
df

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
#Rename columns 
df.columns = ['label','message']

In [7]:
df

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [8]:
#Convert Labels into Numbers
df['label'] = df['label'].map({
    'ham':0,
    'spam':1
})

In [9]:
df

      label                                            message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567      1  This is the 2nd time we have tried 2 contact u...
5568      0              Will Ì_ b going to esplanade fr home?
5569      0  Pity, * was in mood for that. So...any other s...
5570      0  The guy did some bitching but I acted like i'd...
5571      0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [10]:
#Convert Text to Lowercase
df.loc[:, 'message'] = df['message'].str.lower()

In [11]:
df

      label                                            message
0         0  go until jurong point, crazy.. available only ...
1         0                      ok lar... joking wif u oni...
2         1  free entry in 2 a wkly comp to win fa cup fina...
3         0  u dun say so early hor... u c already then say...
4         0  nah i don't think he goes to usf, he lives aro...
...     ...                                                ...
5567      1  this is the 2nd time we have tried 2 contact u...
5568      0              will ì_ b going to esplanade fr home?
5569      0  pity, * was in mood for that. so...any other s...
5570      0  the guy did some bitching but i acted like i'd...
5571      0                         rofl. its true to its name

[5572 rows x 2 columns]

In [12]:
#Remove Punctuation
import string 
df['message'] = df['message'].str.replace(
    f'[{string.punctuation}]',
    '',
    regex=True
)

In [13]:
df.head()

   label                                            message
0      0  go until jurong point crazy available only in ...
1      0                            ok lar joking wif u oni
2      1  free entry in 2 a wkly comp to win fa cup fina...
3      0        u dun say so early hor u c already then say
4      0  nah i dont think he goes to usf he lives aroun...

In [16]:
#Convert Text into Numerical Form
#TF-IDF Vectorizer

#Import Vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

#Create object
tfidf = TfidfVectorizer() 

#Convert messages
X = tfidf.fit_transform(df['message'])

#Target variable
y = df['label']

In [18]:
#Split Dataset

#import libraries 
from sklearn.model_selection import train_test_split

#Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [20]:
#Train Machine Learning Model
#import libraries
from sklearn.naive_bayes import MultinomialNB 

#Create model
model = MultinomialNB() 

#Train model
model.fit(X_train, y_train)

MultinomialNB()

In [21]:
#Make Predictions
y_pred = model.predict(X_test)

In [22]:
#Check Accuracy
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.95695067264574

In [24]:
#Test Custom Message

#Create message
msg = ["Congratulations! You won free tickets"] 

#Convert into vector
msg_vector = tfidf.transform(msg) 

#Predict
prediction = model.predict(msg_vector)
print(prediction)

[1]

In [25]:
msg = ["Hey, are you coming to college today?"]

msg_vector = tfidf.transform(msg)

prediction = model.predict(msg_vector)

print(prediction)

[0]

In [29]:
msg = ["Hey, are you coming to college today?"]

msg_vector = tfidf.transform(msg)

prediction = model.predict(msg_vector)

print("Prediction:", prediction)

if prediction == 1:
    print("Message is Spam")
else:
    print("Message is Normal")

Prediction: [0]
Message is Normal